language: ruby
branches:
  only:
    - master
    - /^[Rr]elease-[1-9][0-9]*\.[0-9]+\.[0-9]+$/
    - /^[1-9][0-9]*\.[0-9]+\.[0-9]+(\-(alpha|beta|rc)(\.[1-9][0-9]*)?)?$/
install:
- gem install jekyll
- chmod ugo+x _scripts/*.sh
- chmod ugo+x _scripts/*/*.sh
script:
- jekyll build

env:
  global:
  - GH_REPO: https://github.com/zpbappi/travis-ci-exp.git

after_success:
- npm install ci-npm-publish
- _scripts/release.sh

