language: ruby
branches:
  except:
    - dev
install:
- gem install jekyll
- chmod ugo+x _scripts/utility.sh
- chmod ugo+x _scripts/build.sh
script:
- jekyll build

env:
  global:
  - GH_REPO: https://github.com/zpbappi/travis-ci-exp.git

after_success:
- _scripts/build.sh

