language: ruby
install:
- gem install jekyll
script:
- jekyll build
- git remote set-url --push origin $GH_REPO
- git config user.name $GIT_NAME
- git config user.email $GIT_EMAIL
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git add -A
- git commit -m "[ci skip] Travis Build - $TRAVIS_BUILD_NUMBER"
- git push --force --quiet origin HEAD:master > /dev/null 2>&1
- rm -r .git/credentials

branches:
  only:
    - master
env:
  global:
    - GH_REPO: https://github.com/zpbappi/travis-ci-exp.git