language: ruby
install:
- gem install jekyll
script:
- jekyll build
- git add -A
- git remote set-url --push origin $GH_REPO
- git config user.name $GIT_NAME
- git config user.email $GIT_EMAIL
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- echo "[ci skip] Travis Build - ${TRAVIS_BUILD_NUMBER}" > commit.txt
- cat ./commit.txt
- git commit --file ./commit.txt
- rm -r commit.txt
- git push origin HEAD:master
- rm -r .git/credentials

branches:
  only:
    - master
env:
  global:
    - GH_REPO: https://github.com/zpbappi/travis-ci-exp.git