language: ruby
rvm:
 - "2.2.2"
install:
 - gem install github-pages
 - gem install travis
script:
 - jekyll build
 - echo $GIT_NAME
 - echo $GH_TOKEN
 - travis login --github-token $GH_TOKEN
 - git config user.name $GIT_NAME
 - git config user.email $GIT_EMAIL
 - git add --all
 - git commit -m "[ci skip] built with travis ci"
 - git push origin master