language: ruby 
install:
- gem install jekyll
- chmod ugo+x ./script.sh
script:
- ./script.sh

branches:
  only:
    - master
env:
  global:
    - GH_REPO: https://github.com/zpbappi/travis-ci-exp.git

deploy:
  provider: releases
  api-key: $GH_KEY
  file:
    - _site/README.html
  skip_cleanup: true
  on:
    all_branches: true