language: ruby
branches:
  except:
    - dev
install:
- gem install jekyll
- chmod ugo+x _scripts/*.sh
- chmod ugo+x _scripts/*/*.sh
script:
- jekyll build

env:
  global:
  - GH_REPO: https://github.com/zpbappi/travis-ci-exp.git

after_success:
- _scripts/release.sh

